# Makefile for building the fortran libraries in the CURP program
#

CURP_HOME = ../../
include $(CURP_HOME)/lib/Makefile.in

##### Target definitions #####

install: lib_calrdf.so lib_calvolume.so lib_sink.so lib_voronoi.so

