# Makefile for building the utility scripts in the CURP program
#

CURP_HOME = ../
include $(CURP_HOME)/lib/Makefile.in

##### Target definitions #####

install: lib_acf.so lib_pickup.so lib_distance.so

