name: Create built CURP package (wheel files) for distribution

on:
  push:
    branches:
      - feature/generate-built-package-automatically

jobs:
  manylinux-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
    
      - name: Install building dependencies (cibuildwheel, etc.)
        run: |
          python -m pip install -U cibuildwheel

      - name: Build wheels using cibuildwheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse