name: Create built CURP package (wheel files) for PyPI distribution

on:
  push:
    branches:
      - feature/generate-built-package-automatically

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.platform }} ${{ matrix.arch }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [manylinux, musllinux]
        arch: [x86_64, i686]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libnetcdf-dev libhdf5-dev graphviz-dev libopenmpi-dev

      - name: Install auditwheel
        run: |
          pip install auditwheel

      - name: Verify gfortran installation
        run: |
          gfortran --version
          which gfortran

      - name: Build wheels using cibuildwheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp36-*
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_PLATFORM: ${{ matrix.platform }}
        with:
          output-dir: ./temp

      - name: Include external dependencies
        run: |
          auditwheel repair ./temp/*.whl -w ./dist

      - name: Upload artifacts to dist/ directory
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.platform }}-${{ matrix.arch }}
          path: ./dist/*.whl
