name: Create built CURP package (wheel files) for distribution

on:
  push:
    branches:
      - feature/generate-built-package-automatically

jobs:
  manylinux-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
    
      - name: Install building dependencies (cibuildwheel, etc.)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -U pip setuptools wheel
          pip install -U cibuildwheel

      - name: Build wheel using cibuildwheel
        run: |
          cibuildwheel --output-dir wheelhouse .

