name: Create built CURP package (wheel files) for PyPI distribution

on:
  push:
    branches:
      - feature/generate-built-package-automatically

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-13]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build wheels using cibuildwheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp36-*
          CIBW_BUILD_VERBOSITY: 1
        with:
          output-dir: ./dist

      - name: Upload artifacts to dist/ directory
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
