name: Create built CURP package (wheel files) for PyPI distribution

on:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies for ${{ matrix.os }}
        run: |
          if [[ ${{ matrix.os }} == "ubuntu-20.04" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential gfortran libnetcdf-dev libhdf5-dev graphviz-dev libopenmpi-dev
          elif [[ ${{ matrix.os }} == "macos-13" ]]; then
            brew install gcc netcdf graphviz open-mpi
            # Ensure gfortran is linked correctly
            brew link --overwrite gcc
            # Add gfortran to PATH
            echo "export PATH=\"$(brew --prefix gcc)/bin:\$PATH\"" >> $GITHUB_ENV
          fi

      - name: Install auditwheel
        run: |
          pip install auditwheel

      - name: Verify gfortran installation
        run: |
          gfortran --version
          which gfortran

      - name: Build wheels using cibuildwheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS: x86_64
          CIBW_BUILD: cp36-*
          CIBW_BUILD_VERBOSITY: 3
        with:
          output-dir: ./dist
      
      - name: Check external libraries are bundled
        run: |
          for whl in dist/Curp-*.whl; do
            echo "=== Inspecting $whl ==="
            unzip -l "$whl" | grep "\.so" || echo "(No .so found)"
            auditwheel show "$whl"
            echo
          done

      - name: Upload artifacts to dist/ directory
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl

      - name: Upload built package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/