name: Deploy document pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    
    - name: Install sphinx
      run: pip install -U sphinx sphinx-rtd-theme sphinx-copybutton
    
    - name: Build pages
      run: sphinx-build -b dirhtml -c docs/source docs/source docs/_build

    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/
        cname: curp.jp
